server:
  port: 7071
  servlet:
    context-path: /ptm-login

spring:
  application:
    name: ptm-login
    
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}