package com.ptm.main.entity.test;
// Generated Nov 14, 2020, 7:25:24 AM by Hibernate Tools 5.2.12.Final

import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "ptm_dev", uniqueConstraints = { @UniqueConstraint(columnNames = "menu_key"),
		@UniqueConstraint(columnNames = "menu_url") })
public class Menu implements java.io.Serializable {

	@Id

	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@Column(name = "menu_key", unique = true, nullable = false, length = 50)
	private String menuKey;

	@Column(name = "menu_name", nullable = false, length = 50)
	private String menuName;

	@Column(name = "menu_url", unique = true, nullable = false, length = 50)
	private String menuUrl;

	@Column(name = "menu_type", nullable = false, length = 50)
	private String menuType;

	@Column(name = "serial_no", nullable = false)
	private int serialNo;

	@Column(name = "enabled", nullable = false, length = 5)
	private String enabled;

	@Column(name = "created_by", nullable = false)
	private int createdBy;

	@Column(name = "created_on", nullable = false, length = 19)
	@CreationTimestamp
	private LocalDateTime createdOn;

	@Column(name = "updated_by")
	private int updatedBy;

	@Column(name = "updated_on", length = 19)
	@UpdateTimestamp
	private LocalDateTime updatedOn;

	public Menu() {
	}

	public Menu(int id, String menuKey, String menuName, String menuUrl, String menuType, int serialNo, String enabled,
			int createdBy, LocalDateTime createdOn) {
		this.id = id;
		this.menuKey = menuKey;
		this.menuName = menuName;
		this.menuUrl = menuUrl;
		this.menuType = menuType;
		this.serialNo = serialNo;
		this.enabled = enabled;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
	}

	public Menu(int id, String menuKey, String menuName, String menuUrl, String menuType, int serialNo, String enabled,
			int createdBy, LocalDateTime createdOn, int updatedBy, LocalDateTime updatedOn) {
		this.id = id;
		this.menuKey = menuKey;
		this.menuName = menuName;
		this.menuUrl = menuUrl;
		this.menuType = menuType;
		this.serialNo = serialNo;
		this.enabled = enabled;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMenuKey() {
		return this.menuKey;
	}

	public void setMenuKey(String menuKey) {
		this.menuKey = menuKey;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	public String getMenuType() {
		return this.menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	public int getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(int serialNo) {
		this.serialNo = serialNo;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public LocalDateTime getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(LocalDateTime createdOn) {
		this.createdOn = createdOn;
	}

	public int getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(int updatedBy) {
		this.updatedBy = updatedBy;
	}

	public LocalDateTime getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(LocalDateTime updatedOn) {
		this.updatedOn = updatedOn;
	}

}
