package com.web.ptm.entity.test;
// Generated Nov 14, 2020, 7:25:24 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IndiaState generated by hbm2java
 */
@Entity
@Table(name = "india_state", catalog = "ptm_dev")
public class IndiaState implements java.io.Serializable {

	@Id

	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@Column(name = "capital", nullable = false, length = 50)
	private String capital;

	@Column(name = "name", nullable = false, length = 50)
	private String name;

	public IndiaState() {
	}

	public IndiaState(int id, String capital, String name) {
		this.id = id;
		this.capital = capital;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCapital() {
		return this.capital;
	}

	public void setCapital(String capital) {
		this.capital = capital;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
