package com.web.ptm.entity.test;
// Generated Nov 14, 2020, 7:25:24 AM by Hibernate Tools 5.2.12.Final

import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * SubMenu generated by hbm2java
 */
@Entity
@Table(name = "sub_menu", catalog = "ptm_dev", uniqueConstraints = { @UniqueConstraint(columnNames = "sub_menu_url"),
		@UniqueConstraint(columnNames = "action_key") })
public class SubMenu implements java.io.Serializable {

	@Id

	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@Column(name = "menu_id", nullable = false)
	private int menuId;

	@Column(name = "action_key", unique = true, nullable = false, length = 50)
	private String actionKey;

	@Column(name = "action_type", nullable = false, length = 13)
	private String actionType;

	@Column(name = "command_name", nullable = false, length = 50)
	private String commandName;

	@Column(name = "created_on", nullable = false, length = 19)
	@CreationTimestamp
	private LocalDateTime createdOn;

	@Column(name = "deleted", nullable = false, length = 5)
	private String deleted;

	@Column(name = "enabled", nullable = false, length = 5)
	private String enabled;

	@Column(name = "sub_menu_name", nullable = false, length = 50)
	private String subMenuName;

	@Column(name = "sub_menu_url", unique = true, nullable = false, length = 50)
	private String subMenuUrl;

	@Column(name = "updated_on", length = 19)
	@UpdateTimestamp
	private LocalDateTime updatedOn;

	@Column(name = "created_by", nullable = false)
	private int createdBy;

	@Column(name = "updated_by")
	private int updatedBy;

	public SubMenu() {
	}

	public SubMenu(int id, int menuId, String actionKey, String actionType, String commandName, LocalDateTime createdOn,
			String deleted, String enabled, String subMenuName, String subMenuUrl, int createdBy) {
		this.id = id;
		this.menuId = menuId;
		this.actionKey = actionKey;
		this.actionType = actionType;
		this.commandName = commandName;
		this.createdOn = createdOn;
		this.deleted = deleted;
		this.enabled = enabled;
		this.subMenuName = subMenuName;
		this.subMenuUrl = subMenuUrl;
		this.createdBy = createdBy;
	}

	public SubMenu(int id, int menuId, String actionKey, String actionType, String commandName, LocalDateTime createdOn,
			String deleted, String enabled, String subMenuName, String subMenuUrl, LocalDateTime updatedOn,
			int createdBy, int updatedBy) {
		this.id = id;
		this.menuId = menuId;
		this.actionKey = actionKey;
		this.actionType = actionType;
		this.commandName = commandName;
		this.createdOn = createdOn;
		this.deleted = deleted;
		this.enabled = enabled;
		this.subMenuName = subMenuName;
		this.subMenuUrl = subMenuUrl;
		this.updatedOn = updatedOn;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	public String getActionKey() {
		return this.actionKey;
	}

	public void setActionKey(String actionKey) {
		this.actionKey = actionKey;
	}

	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	public String getCommandName() {
		return this.commandName;
	}

	public void setCommandName(String commandName) {
		this.commandName = commandName;
	}

	public LocalDateTime getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(LocalDateTime createdOn) {
		this.createdOn = createdOn;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getSubMenuName() {
		return this.subMenuName;
	}

	public void setSubMenuName(String subMenuName) {
		this.subMenuName = subMenuName;
	}

	public String getSubMenuUrl() {
		return this.subMenuUrl;
	}

	public void setSubMenuUrl(String subMenuUrl) {
		this.subMenuUrl = subMenuUrl;
	}

	public LocalDateTime getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(LocalDateTime updatedOn) {
		this.updatedOn = updatedOn;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public int getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(int updatedBy) {
		this.updatedBy = updatedBy;
	}

}
