package com.web.ptm.entity.test;
// Generated Nov 14, 2020, 7:25:24 AM by Hibernate Tools 5.2.12.Final

import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "ptm_dev", uniqueConstraints = @UniqueConstraint(columnNames = { "designation_id",
		"submenu_command_id" }))
public class UserRole implements java.io.Serializable {

	@Id

	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@Column(name = "t_designation_name", nullable = false, length = 50)
	private String TDesignationName;

	@Column(name = "t_menu_cmd_name", nullable = false, length = 50)
	private String TMenuCmdName;

	@Column(name = "created_on", nullable = false, length = 19)
	@CreationTimestamp
	private LocalDateTime createdOn;

	@Column(name = "deleted", nullable = false, length = 5)
	private String deleted;

	@Column(name = "enabled", nullable = false, length = 5)
	private String enabled;

	@Column(name = "updated_on", length = 19)
	@UpdateTimestamp
	private LocalDateTime updatedOn;

	@Column(name = "created_by", nullable = false)
	private int createdBy;

	@Column(name = "designation_id", nullable = false)
	private int designationId;

	@Column(name = "submenu_command_id", nullable = false)
	private int submenuCommandId;

	@Column(name = "updated_by")
	private int updatedBy;

	public UserRole() {
	}

	public UserRole(int id, String TDesignationName, String TMenuCmdName, LocalDateTime createdOn, String deleted,
			String enabled, int createdBy, int designationId, int submenuCommandId) {
		this.id = id;
		this.TDesignationName = TDesignationName;
		this.TMenuCmdName = TMenuCmdName;
		this.createdOn = createdOn;
		this.deleted = deleted;
		this.enabled = enabled;
		this.createdBy = createdBy;
		this.designationId = designationId;
		this.submenuCommandId = submenuCommandId;
	}

	public UserRole(int id, String TDesignationName, String TMenuCmdName, LocalDateTime createdOn, String deleted,
			String enabled, LocalDateTime updatedOn, int createdBy, int designationId, int submenuCommandId,
			int updatedBy) {
		this.id = id;
		this.TDesignationName = TDesignationName;
		this.TMenuCmdName = TMenuCmdName;
		this.createdOn = createdOn;
		this.deleted = deleted;
		this.enabled = enabled;
		this.updatedOn = updatedOn;
		this.createdBy = createdBy;
		this.designationId = designationId;
		this.submenuCommandId = submenuCommandId;
		this.updatedBy = updatedBy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTDesignationName() {
		return this.TDesignationName;
	}

	public void setTDesignationName(String TDesignationName) {
		this.TDesignationName = TDesignationName;
	}

	public String getTMenuCmdName() {
		return this.TMenuCmdName;
	}

	public void setTMenuCmdName(String TMenuCmdName) {
		this.TMenuCmdName = TMenuCmdName;
	}

	public LocalDateTime getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(LocalDateTime createdOn) {
		this.createdOn = createdOn;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public LocalDateTime getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(LocalDateTime updatedOn) {
		this.updatedOn = updatedOn;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public int getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(int designationId) {
		this.designationId = designationId;
	}

	public int getSubmenuCommandId() {
		return this.submenuCommandId;
	}

	public void setSubmenuCommandId(int submenuCommandId) {
		this.submenuCommandId = submenuCommandId;
	}

	public int getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(int updatedBy) {
		this.updatedBy = updatedBy;
	}

}
